### ISSUE TITLE
crash under 4.1.1 stable

### ISSUE THREAD

**Issue by Kalamster** [Ericdowney/SignalVisualizer#1]
clicking "generate" will freeze Godot for a moment, then unfortunately crash to desktop every time.

**Comment by Ericdowney** [comment]
Sorry about this! I believe this is due to a call to `GraphEdit`'s `arrange_nodes()` function. I should have a new version pushed out in the next day to toggle that off.

**Comment by Kalamster** [comment]
That's great, thank you!

**Comment by Ericdowney** [comment]
@Kalamster I've published a new version. Please let me know if it doesn't resolve your issue.

**Comment by Kalamster** [comment]
It works now, thanks for fixing the plugin! To get the autoload singelton to show up however, I had to copy the whole directory (i.e. the dir containing project.godot and all other dirs), not only the /addons folder.

**Comment by Ericdowney** [comment]
That's great to hear! I'm going to close this issue but I'll start another one for the new problem.
