### ISSUE TITLE
Cannot detected the signals using code with "connect"

### ISSUE THREAD

**Issue by dreanzy** [Ericdowney/SignalVisualizer#4]
**Describe the bug**
Cannot detected the signals using code with "connect" like this:
```
func _ready():
	$Timer.timeout.connect(on_timer_timeout)
```

And thans for making the plugin.

**Comment by tehelka-gamedev** [comment]
I realised the same thing while testing it today. The thing is that the code uses the method `get_signal_connection_list` which returns an empty list `[]` for cases like this. In your example, the `_ready()` function is called only when the node is created during the game, but then in the editor the signal is not connected.
I guess the addon code would need to be rewrote to analyse the GDScript files to make it work ? But that can be tricky, as some signals connections can happen during the game or depending on some conditions.

**Comment by Ericdowney** [comment]
Hey! Sorry for the late response. Tehekla is correct. The signal connections are scanned at the time the generate graph button is pressed and it looks at the scene in the editor. 

Dynamic signals are on my roadmap but does not work right now. I'm going to close out this issue but I'll create an enhancement issue to address this.

**Comment by Ericdowney** [comment]
SignalDebugger enhancement https://github.com/Ericdowney/SignalVisualizer/issues/5
