### ISSUE TITLE
whenever the plugin is active, shows save dialogue everytime even if nothing is edited

### ISSUE THREAD

**Issue by RakibRyan** [Ericdowney/SignalVisualizer#7]
Would it be possible to make this go away. it becomes annoying when I haven't even edited anything.
godot4.2.1 mono 
![Screenshot (115)](https://github.com/Ericdowney/SignalVisualizer/assets/85598032/e199fd87-1eab-41d0-896c-4559639e048c)

**Comment by Ericdowney** [comment]
Apologies for the delay. This is fixed as of [Release v1.6.0](https://github.com/Ericdowney/SignalVisualizer/releases/tag/1.6.0)
