### ISSUE TITLE
Add 4.2 support for SignalDebugger. Doesn't work in 4.2+ (but works on 4.1)

### ISSUE THREAD

**Issue by GustJc** [Ericdowney/SignalVisualizer#8]
The new SignalDebugger dock doesn't work in 4.2+
It doesn't show the tree and no signals are shown after starting.
![image](https://github.com/Ericdowney/SignalVisualizer/assets/3084189/3548710c-e72c-4405-a2f8-2bab253c36d0)

It worked correctly o 4.1. It only stops working on 4.2+.
No errors. Just don't do anything.

---
And as a side note. Version 1.3.0 no longer works with Godot 4.0. Only 4.1+
Trying to generate a Graph in 4.0 you get this error.
![image](https://github.com/Ericdowney/SignalVisualizer/assets/3084189/3f5caa90-ad03-4352-932d-43bd16660219)
So downloading the version from the assetlibrary won't work on 4.0 anymore.
Maybe update the asset library version to 4.1 now?
![image](https://github.com/Ericdowney/SignalVisualizer/assets/3084189/bdb735f5-428a-4fc7-8e80-a82e8bcfe45b)

**Comment by LaurentOngaro** [comment]
I can confirm this issue. 
The signal tree is empty after clicking on the "Start" button in the Signal Debugger. 
No error or Message is displayed in the output or error tabs neither

**Comment by Ericdowney** [comment]
Apologies on the delay, this should now be fixed on the latest release. https://github.com/Ericdowney/SignalVisualizer/releases/tag/1.4.1.
